### ISSUE TITLE
Crashes on new username search and identity restore

### ISSUE THREAD

**Issue by Dubz** [surespot/android#159]
Debugger output:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.twofours.surespot, PID: 12188
    java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found
        at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1333)
        at okhttp3.HttpUrl.get(HttpUrl.java:916)
        at okhttp3.Request$Builder.url(Request.java:165)
        at com.twofours.surespot.network.NetworkController.postJSON(NetworkController.java:309)
        at com.twofours.surespot.network.NetworkController.validate(NetworkController.java:857)
        at com.twofours.surespot.identity.IdentityController.importIdentity(IdentityController.java:491)
        at com.twofours.surespot.backup.ImportIdentityActivity$6$1.handleResponse(ImportIdentityActivity.java:417)
        at com.twofours.surespot.backup.ImportIdentityActivity$6$1.handleResponse(ImportIdentityActivity.java:407)
        at com.twofours.surespot.utils.UIUtils$1.onClick(UIUtils.java:95)
        at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:184)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7263)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
E/ACRA: ACRA caught a IllegalArgumentException for com.twofours.surespot
    java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found
        at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1333)
        at okhttp3.HttpUrl.get(HttpUrl.java:916)
        at okhttp3.Request$Builder.url(Request.java:165)
        at com.twofours.surespot.network.NetworkController.postJSON(NetworkController.java:309)
        at com.twofours.surespot.network.NetworkController.validate(NetworkController.java:857)
        at com.twofours.surespot.identity.IdentityController.importIdentity(IdentityController.java:491)
        at com.twofours.surespot.backup.ImportIdentityActivity$6$1.handleResponse(ImportIdentityActivity.java:417)
        at com.twofours.surespot.backup.ImportIdentityActivity$6$1.handleResponse(ImportIdentityActivity.java:407)
        at com.twofours.surespot.utils.UIUtils$1.onClick(UIUtils.java:95)
        at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:184)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7263)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

I tried this with master and b81 branches. No changes to the script, added google-services.json, and the missing raw/configuration.properties file referenced in PR #145

**Comment by Dubz** [comment]
Fixed. Had to adjust the configuration.properties to be baseUrlProd and baseUrlLocal
